export const all_genres = [
  'Action',
  'Indie',
  'Adventure',
  'RPG',
  'Strategy',
  'Shooter',
  'Casual',
  'Simulation',
  'Puzzle',
  'Arcade',
  'Platformer',
  'Racing',
  'Massively Multiplayer',
  'Sports',
  'Fighting',
  'Family',
  'Board Games',
  'Educational',
  'Card',
];

export const all_platforms = [
  'Android',
  'iOS',
  'Nintendo DS',
  'Nintendo 3DS',
  'Nintendo Switch',
  'PC',
  'PlayStation 3',
  'PlayStation 4',
  'PlayStation 5',
  'Wii U',
  'Xbox One',
  'Xbox Series S/X',
];
